baseURL = 'https://zhumeme.github.io'
languageCode = 'en-us'
title = 'zhumeme blog'
theme = 'nightfall'

[params]
author = "Mr Hugo"
user = "hello"
hostname = "gohugo.io"

[[params.social]]
key = 3
name = "email"
url = "mailto:email@example.com"
