baseURL = 'https://zhumeme.github.io'
languageCode = 'zh-cn'
title = 'zhumeme blog'
theme = 'nightfall'

[params]
disqusShortname = 'zhumeme.github.io'
author = "zhumeme"
user = "zhumeme"
hostname = "zhumeme.github.io"

[[params.social]]
key = 3
name = "email"
url = "mailto:chyloveslife@gmail.com"

[menu]
[[menu.header]]
name = "posts"
weight = 0
url = "/posts"

[permalinks]
posts = '/:year/:month/:title/'